version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: gomod
    directories:
      - /
      - /third_party/x-vt
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /promo
    schedule:
      interval: weekly
    versioning-strategy: increase
    open-pull-requests-limit: 5
