#!/bin/sh
# Regenerates THIRD_PARTY_NOTICES.md; run after changing dependencies or copying code.
set -eu

root=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
cd "$root"
export GOFLAGS=-tags=novulkan
modcache=$(mise exec -- go env GOMODCACHE)
out=THIRD_PARTY_NOTICES.md

license_file() {
    for name in LICENSE LICENSE.md LICENSE.txt LICENCE COPYING UNLICENSE; do
        if [ -f "$1/$name" ]; then
            printf '%s\n' "$1/$name"
            return 0
        fi
    done
    return 1
}

# why: the module cache escapes upper-case letters as !lower.
escape() {
    printf '%s' "$1" | sed 's/\([A-Z]\)/!\1/g' | tr '[:upper:]' '[:lower:]'
}

{
    cat docs/credits-copied.md
    printf '\n## Go modules linked into pitwall\n\n'
    printf 'Generated by `scripts/notices.sh` from `go list -deps ./cmd/pitwall`.\n'
    mise exec -- go list -deps -f '{{if .Module}}{{.Module.Path}} {{.Module.Version}}{{end}}' ./cmd/pitwall |
        sort -u | grep -v '^github.com/quanticstudios/pitwall' |
        while read -r path ver; do
            if [ "$path" = github.com/charmbracelet/x/vt ]; then
                dir=third_party/x-vt
            else
                dir="$modcache/$(escape "$path")@$ver"
            fi
            printf '\n### %s %s\n\n' "$path" "$ver"
            if file=$(license_file "$dir"); then
                printf '```text\n'
                cat "$file"
                printf '```\n'
            else
                printf 'No license file found in the module; see its repository.\n'
            fi
        done
} >"$out"
printf 'Wrote %s\n' "$out"
